/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.left.join;

import java.util.*;

public class App {


    public static void main(String[] args) {
        HashMap<String,String> h1= new HashMap<>();
        h1.put("diligent","employed");
        h1.put("fond","enamored");
        h1.put("guide","usher");
        h1.put("outfit","garb");
        h1.put("wrath","anger");

        HashMap<String,String> h2= new HashMap<>();
        h2.put("diligent","idle");
        h2.put("fond","averse");
        h2.put("guide","follow");
        h2.put("flow","jam");
        h2.put("wrath","delight");

//        System.out.println(hashmapLeftJoin(h1,h2));
    }


    public  List<String> hashmapLeftJoin(HashMap<String,String> hashMap1,HashMap<String,String> hashMap2){
        List<String> JoinData= new ArrayList<>();

        /// map over the hash set entity
        for (Map.Entry<String, String> s :hashMap1.entrySet()){
            JoinData.add( "["+ s.getKey() + ", "+ s.getValue() + ", "+ hashMap2.getOrDefault(s.getKey(), "null") + " ]" );
        }
        return JoinData;
    }
}
