/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    BracketValidation app = new BracketValidation();;

    @Test
    void happyPath() {
        assertEquals(app.stackQueueBrackets("()[[Extra Characters]]"), true);
        assertEquals(app.stackQueueBrackets("{}{Code}[Fellows](())"), true);
        assertEquals(app.stackQueueBrackets("{}(){}"), true);
        assertEquals(app.stackQueueBrackets("{}"), true);
    }

    @Test
    void ExpectedFailure() {
        assertEquals(app.stackQueueBrackets("[({}]"), false);
        assertEquals(app.stackQueueBrackets("(]("), false);
        assertEquals(app.stackQueueBrackets("{(})"), false);
    }

    @Test
    void EdgeCases(){
        assertEquals(app.stackQueueBrackets(""),false);
        assertEquals(app.stackQueueBrackets("mohammed"),false);
        assertEquals(app.stackQueueBrackets("1234"),false);
    }
}
