/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Singly.Linked.Lists;

import org.junit.jupiter.api.Test;


import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    void CanInstantiate(){
        LinkedList test = new LinkedList();
        assertEquals(0,test.size);

    }

    @Test
    void CanInsert (){
        LinkedList test = new LinkedList();
        test.insert(1);
assertEquals(1,test.head.value);

    }
    @Test
    void CanInsertMultiple (){
        LinkedList test = new LinkedList();
test.insert(1);
test.insert(2);
test.insert(3);
test.insert(4);


assertEquals(4,test.head.value);
assertEquals(4,test.size);
    }
    @Test
    void ExistsValue(){
        LinkedList test = new LinkedList();
        test.insert(1);
        test.insert(2);
        test.insert(3);
        test.insert(4);
        boolean result = test.includes(4);
        assertEquals(true,result);
    }
    @Test
    void PrintAllValue(){
        LinkedList test = new LinkedList();
        test.insert(1);
        test.insert(2);
        test.insert(3);
        test.insert(4);
        test.ToString();
    }
}
