/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


    }


    public   int[] InsertionSort(int[] arr){
        for (int i =1 ;i< arr.length;i++){
            int j = i -1;
            int temp = arr[i];
            while (j>=0 && temp <arr[j]){
                arr[j+1]=arr[j];
                j--;
            }
            arr[j+1] =temp;

        }
        return arr;
    }
}
