/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;

import Challenge.HashTable.HashTable;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        HashTable<String,String> test= new HashTable<>(5);
        test.put("Once","mohammed");
        test.put("upon","nidal");
        test.put("time","jj");
        test.put("was","oo");
        test.put("a","a");
        test.put("a","oo");
        test.put("there","oo");
        test.put("there","oo");
        test.put("there","oo");











       /*
       challenge 31
        */
        System.out.println(HashTableMethod.repeatedWord("a"));

    }
}
