/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }


    @Test
    void HappyBath(){
        LinkedList test =new LinkedList();
        test.append(1);
        test.insertBefore(1,2);
        assertTrue(test.includes(1));
    }

    @Test
    void HappyBath2(){
        LinkedList test =new LinkedList();
        test.append(1);
        test.append(2);
        test.insertAfter(2,3);

        assertTrue(test.includes(3));
    }

    @Test
    void ExpectedFailure(){
        LinkedList test =new LinkedList();
        test.append(1);
        test.append(2);
        test.insertAfter(3,5);

        assertFalse(test.includes(5));
    }

    @Test
    void EdgeCase(){
        LinkedList test =new LinkedList();
        test.insertAfter(10,5);
        assertFalse(test.includes(5));
    }


}
