/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;

import java.util.ArrayList;
import java.util.LinkedList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Cat cat = new Cat("test1");
        Cat cat2 = new Cat("test2");
        AnimalShelter animalShelter = new AnimalShelter();
        animalShelter.enqueue(cat);
        animalShelter.enqueue(cat2);
        System.out.println(animalShelter.dequeue("cat"));

        System.out.println(animalShelter);

    }
}
