/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;

import NodeTree.Node;
import Tree.BinarySearchTree;
import Tree.BinaryTree;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        BinarySearchTree<Integer> stringBinarySearchTree = new BinarySearchTree<>();
         stringBinarySearchTree.Add(10);
        stringBinarySearchTree.Add(2);
        stringBinarySearchTree.Add(50);
        stringBinarySearchTree.Add(4);
        stringBinarySearchTree.Add(0);
        stringBinarySearchTree.preOrder();
        System.out.println("---------------------------\n" + "postOrder"); // it returns an array
        System.out.println(stringBinarySearchTree.postOrder());
        System.out.println("---------------------------\n" + "inOrder");
        stringBinarySearchTree.inOrder();

        System.out.println(stringBinarySearchTree.Contains(10));

    }



}
