/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;

import Challenge.Queue.PseudoQueue;
import Challenge.Queue.QueueDs;
import Challenge.Stack.StackDs;

import java.util.ArrayDeque;
import java.util.Queue;
import java.util.Stack;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
//        StackDs stackDs = new StackDs();
//        stackDs.Push(1);
//        stackDs.Push(2);
//        System.out.println(stackDs.top);
//        System.out.println(stackDs);
//        System.out.println("-----------------------------------------------------------");
//
//        QueueDs queueDs = new QueueDs();
//        queueDs.enqueue(10);
//        queueDs.enqueue(20);
//        queueDs.enqueue(30);
//        System.out.println(queueDs.rear);
//        System.out.println( queueDs.toString());

        PseudoQueue pseudoQueue = new PseudoQueue();
        pseudoQueue.enqueue(10);
        pseudoQueue.enqueue(20);
        pseudoQueue.enqueue(30);
        System.out.println(pseudoQueue.dequeue());
        System.out.println(pseudoQueue);
        // build in  Queue for test my code .
        Queue queue = new ArrayDeque();
        queue.add(10);
        queue.add(20);
        queue.add(30);
        queue.poll();
        queue.toString();
        System.out.println(queue);

    }
}
