/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;

import Tree.BinarySearchTree;
import Tree.BinaryTree;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }


    @Test
    void instantiateAnEmptyTree(){
        BinaryTree<String> stringBinaryTree = new BinaryTree<>();
    }
    @Test
    void instantiateSingleRoot(){
        BinaryTree<String> stringBinaryTree = new BinaryTree<>();

    }

    @Test
    void BinarySearch(){
        BinarySearchTree<Integer> tree = new BinarySearchTree<>();
        tree.Add(10);
        tree.Add(20);
        tree.Add(30);
    }
}
