/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

@Test
    void testInsertionSort(){
    App classUnderTest = new App();
    assertArrayEquals(new int[]{4,8,15,16,23,42},classUnderTest.InsertionSort(new int[]{8,4,23,42,16,15}));
}

    @Test
    void testInsertionSort2(){
        App classUnderTest = new App();
        assertArrayEquals(new int[]{4,8},classUnderTest.InsertionSort(new int[]{8,4}));
    }
    @Test
    void testInsertionSort3(){
        App classUnderTest = new App();
        assertArrayEquals(new int[]{4},classUnderTest.InsertionSort(new int[]{4}));
    }
    @Test
    void testInsertionSort4(){
        App classUnderTest = new App();
        assertArrayEquals(new int[]{},classUnderTest.InsertionSort(new int[]{}));
    }


}
