/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

//        Arrays.stream(QuickSort(new int[]{8, 4, 23, 42, 16, 15}, 0, 5)).forEach(System.out::println);

    }


    public  int[] QuickSort(int[] arr, int left, int right) {
        if (left < right) {
            int position = Partition(arr, left, right);
            QuickSort(arr, left, position - 1);
            QuickSort(arr, position + 1, right);
        }
        return arr;
    }

    private  int Partition(int[] arr, int left, int right) {
        int pivot = arr[right];
        int low = left - 1;
        for (int i = left; i < right; i++) {
            if (arr[i] <= pivot) {
                low++;
                Swap(arr, i, low);
            }
        }
        Swap(arr, right, low + 1);
        return low + 1;

    }

    private  void Swap(int[] arr, int i, int low) {
        int temp = arr[i];
        arr[i] = arr[low];
        arr[low] = temp;
    }
}
