/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Singly.Linked.Lists;

import DoublyLinkedList.DoublLinkedList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {


    }
}
