/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        LinkedList list1 = new LinkedList();
        list1.append(5);
        list1.append(9);
        LinkedList list2= new LinkedList();
        list2.append(5);
        list2.append(9);
        list2.append(4);
        LinkedList out = new LinkedList();
        out=out.zipLists(list1,list2);
        out.ToString();
//        System.out.println(out.size);
    }
}
