/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        LinkedList test = new LinkedList();
        test.append(6);
        test.append(7);
        test.append(8);
        test.append(7);
        test.append(6);
        System.out.println(test.head.value);

        System.out.println(test.isPalindrome());

    }
}
