/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
LinkedList test = new LinkedList();








test.ToString();

    }
}
