/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        LinkedList test = new LinkedList();
        test.append(0);
        test.append(1);
        test.append(2);
        test.append(3);
        test.append(4);
        test.append(5);
        test.append(6);
        test.append(7);
        test.append(8);



        System.out.println(test.MiddleValueNode());
        test.ToString();


    }
}
