/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        MergeSort(new int[]{8,4,23,42,16,15});
        Arrays.stream(MergeSort(new int[]{8,4,23,42,16,15})).forEach(value -> {
            System.out.print(value + " --> ");
        });
    }

    public static int[]  MergeSort(int[] arr) {
        int n = arr.length;
        if (n > 1) {
            int mid = n / 2;
            int[] left = new int[mid];
            int[] right = new int[n - mid];
            System.arraycopy(arr, 0, left, 0, mid); /// same for (i=0;i<mid;i++)
            System.arraycopy(arr, mid, right, 0, n - mid); /// same for (i=mid;i<n;i++)
            MergeSort(left);
            MergeSort(right);
            return MergeSort(left, right, arr);

        } else return arr;

    }

    private static int[] MergeSort(int[] left, int[] right, int[] arr) {
        int i = 0;
        int j = 0;
        int k = 0;
        while (i < left.length && j < right.length) {
            if (left[i] <= right[j]) {
                arr[k] = left[i];
                i++;
            } else {
                arr[k] = right[j];
                j++;
            }
            k++;
        }
        while (i < left.length) {
            arr[k] = left[i];
            i++;
            k++;
        }

        while (j < right.length) {
            arr[k] = right[j];
            j++;
            k++;
        }
        return arr;
    }







}
