/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge;

import Challenge.Queue.QueueDs;
import Challenge.Stack.StackDs;

import java.util.ArrayDeque;
import java.util.Queue;
import java.util.Stack;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
//        StackDs stackDs = new StackDs();
//        stackDs.Push("mohammed");
//        stackDs.Push("ah");
//        System.out.println("-----------------------------------------------------------");
//
//        QueueDs queueDs = new QueueDs();
//        queueDs.enqueue(10);
//        queueDs.enqueue(20);
//        queueDs.enqueue(30);
//        queueDs.dequeue();
//        System.out.println(queueDs.peek());
//        System.out.println( queueDs.toString());
        QueueDs queueDs = new QueueDs();
        queueDs.enqueue("mohammed");
        queueDs.enqueue("kahled");
        queueDs.enqueue("ahmad");
        queueDs.
    }
}
